### PR TITLE
Update code_names_german.txt

### PR DESCRIPTION
**Pull request by IBFAIT**
Changed ä, ö, ü to ae, oe, ue as flip_card() fails with non-ascii codenames

### CODE REVIEW

**Comment by joshporter1** [comment]
Is this a suitable solution or shall we explore supporting the non-ASCII characters? I have minimal experience with this sort of internationalization but I'm sure something's failing when trying to compare words. 

I'm fine merging this in, so it's up to you which solution we pursue!

**Comment by IBFAIT** [comment]
It's a suitable solution for the german dictionary, yes.

But the french dictionary doesn't work. You can't flip cards with french characters like è, é or œ.

I tried to introduce unicode to the project (server part) but unfortunately I have absolute no experience in programming with python.

**Comment by IBFAIT** [comment]
Hmm. Probably I should switch from Python 2 to 3. Looks like unicode-strings are processed correctly on your server (codewords.tv). Sorry for the confusion...

**Comment by joshporter1** [comment]
Can you confirm the special characters work when using Python 3? I'll check it out as well, but as far as I know the French dictionary has been working with no issues.

**Comment by IBFAIT** [comment]
I do confirm. Special characters work when using Python 3. I apologize for the inconvenience.

**Pull request closed without merging**
